# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jwwwb
email: james@jwwwb.com
description: > # this means to ignore newlines until "baseurl:"
  jwwwb. Home to my projects and ruminations on natural language processing, 
  machine learning, acoustics and life. For some reason I've decided I want 
  to share my thoughts with the world and/or nobody.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.jwwwb.com" # the base hostname & protocol for your site
twitter_username: jwwwbr
github_username:  jwwwb
timezone: Europe/Madrid
future: true

# Build settings
markdown: kramdown